name: Cache Dependencies Test

on:
  push:
    branches:
      - main

jobs:
  cache-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache dependencies
        id: prime-cache-4fb03de
        uses: actions/cache@v4
        with:
          path: ~/.npm    # example Node.js cache, change for Python/etc.
          key: cache-4fb03de

      - name: prime-cache-4fb03de
        run: echo "Cache hit: ${{ steps.prime-cache-4fb03de.outputs.cache-hit }}"
