name: Cache Dependencies Test

on:
  push:
    branches:
      - main

jobs:
  cache-job:
    runs-on: ubuntu-latest
    steps:
      - name: prime-cache-4fb03de
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: cache-4fb03de
        run: |
          echo "Cache hit: ${{ steps.prime-cache-4fb03de.outputs.cache-hit }}"
